export const imagesData = [
  {
    // id: "1",
    name: "Glittery Mules",
    image: require("../images/IMG1.jpg"),
    category: "Mules",
    // color: ["black"],
    price: 18000,
    details: "Glittery Mules with Horse-bit Chain",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "2",
    name: "Black Leather Mules with Monogram",
    image: require("../images/IMG2.jpg"),
    category: "Mules",
    // color: ["black"],
    price: 18000,
    details: "Black Leather Mules with Monogram",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "3",
    name: "Black Glossy and Leather Loafers with Tassels",
    image: require("../images/IMG3.jpg"),
    category: "Loafers",
    // color: ["black"],
    price: 18000,
    details: "Black Glossy and Leather Loafers with Tassels",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "4",
    name: "Black Glossy Lace-Up",
    image: require("../images/IMG4.jpg"),
    category: "Laceup",
    // color: ["black"],
    price: 18000,
    details: "Black Glossy Lace-Up",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "5",
    name: "Black Basket Leather Shoe-Sandals",
    image: require("../images/IMG5.jpg"),
    category: "Shoesandals",
    // color: ["black"],
    price: 18000,
    details: "Black Basket Leather Shoe-Sandals",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "6",
    name: "Black Croc-Skin Leather Loafers with Horse-bit Chain",
    image: require("../images/IMG6.jpg"),
    category: "Loafers",
    // color: ["black"],
    price: 18000,
    details: "Black Croc-Skin Leather Loafers with Horse-bit Chain",
    // shoeSize: ["39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },

  {
    // id: "7",
    name: "Brown Croc-Skin Leather Monkstrap",
    image: require("../images/IMG9.jpg"),
    category: "Monkstrap",
    // color: ["brown"],
    price: 18000,
    details: "Brown Croc-Skin Leather Monkstrap",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "8",
    name: "Blue Suede Slippers with Horse-bit Chain",
    image: require("../images/IMG18.jpg"),
    category: "Slippers",
    // color: ["blue"],
    price: 18000,
    details: "Blue Suede Slippers with Horse-bit Chain",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "9",
    name: "Nude Suede Chelsea Boots",
    image: require("../images/IMG23.jpg"),
    category: "Boots",
    // color: ["nude"],
    price: 25000,
    details: "Nude Suede Chelsea Boots",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "10",
    name: "Gray Suede Chelsea Boots with Buckle",
    image: require("../images/IMG11.jpg"),
    category: "Boots",
    // color: ["gray"],
    price: 25000,
    details: "Gray Suede Chelsea Boots with Buckle",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "11",
    name: "Black Suede Chelsea Boots",
    image: require("../images/IMG20.jpg"),
    category: "Boots",
    // color: ["black"],
    price: 25000,
    details: "Black Suede Chelsea Boots",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "12",
    name: "Brown Suede Chelsea Boots",
    image: require("../images/IMG27.jpg"),
    category: "Boots",
    // color: ["brown"],
    price: 25000,
    details: "Brown Suede Chelsea Boots",
    // shoeSize: ["38", "39", "40", "45", "46", "47"],
  },
  {
    // id: "13",
    name: "Brown Suede Chukka Boots",
    image: require("../images/IMG25.jpg"),
    category: "Boots",
    // color: ["brown"],
    price: 25000,
    details: "Brown Suede Chukka Boots",
    // shoeSize: ["41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "14",
    name: "Blue Leather Slippers",
    image: require("../images/IMG10.jpg"),
    category: "Slippers",
    // color: ["blue"],
    price: 18000,
    details: "Blue Leather Slippers",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44"],
  },
  {
    // id: "15",
    name: "Black Suede Slippers with Buckle",
    image: require("../images/IMG17.jpg"),
    category: "Slippers",
    // color: ["black"],
    price: 18000,
    details: "Black Suede Slippers with Buckle",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "16",
    name: "Black Suede Double-Strapped Birkenstock Slippers",
    image: require("../images/IMG24.jpg"),
    category: "Slippers",
    // color: ["black"],
    price: 18000,
    details: "Black Suede Double-Strapped Birkenstock Slippers",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "17",
    name: "Black Croc-Skin Leather Slippers",
    image: require("../images/IMG26.jpg"),
    category: "Slippers",
    // color: ["black"],
    price: 18000,
    details: "Black Croc-Skin Leather Slippers",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "18",
    name: "Black Leather Birkenstock Slippers",
    image: require("../images/IMG33.jpg"),
    category: "Slippers",
    // color: ["black"],
    price: 18000,
    details: "Black Leather Birkenstock Slippers",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "19",
    name: "Black Croc-Skin Leather Loafers",
    image: require("../images/IMG8.jpg"),
    category: "loafers",
    // color: ["black"],
    price: 18000,
    details: "Black Croc-Skin Leather Loafers",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "20",
    name: "Nude Suede Loafers with Tassels",
    image: require("../images/IMG13.jpg"),
    category: "loafers",
    // color: ["nude"],
    price: 18000,
    details: "Nude Suede Loafers with Tassels",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "21",
    name: "Black Animal-Skin and Plain Leather Shoe-Sandals",
    image: require("../images/IMG15.jpg"),
    category: "shoesandals",
    // color: ["black"],
    price: 18000,
    details: "Black Animal-Skin and Plain Leather Shoe-Sandals",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "22",
    name: "Black Leather Double-Strapped Lace-Up",
    image: require("../images/IMG14.jpg"),
    category: "laceup",
    // color: ["black"],
    price: 18000,
    details: "Black Leather Double-Strapped Lace-Up",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "23",
    name: "Black Glossy and Suede Lace-Up",
    image: require("../images/IMG21.jpg"),
    category: "laceup",
    // color: ["black"],
    price: 18000,
    details: "Black Glossy and Suede Lace-Up",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "24",
    name: "Black Croc-Skin and Plain Leather Lace-Up",
    image: require("../images/IMG32.jpg"),
    category: "laceup",
    // color: ["black"],
    price: 18000,
    details: "Black Croc-Skin and Plain Leather Lace-Up",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "25",
    name: "Black Glossy Lace-Up",
    image: require("../images/IMG35.jpg"),
    category: "laceup",
    // color: ["black"],
    price: 18000,
    details: "Black Glossy Lace-Up",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "26",
    name: "Black Leather and Suede Monkstrap",
    image: require("../images/IMG19.jpg"),
    category: "monkstrap",
    // color: ["black"],
    price: 18000,
    details: "Black Leather and Suede Monkstrap",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "27",
    name: "Black Croc-Skin Leather Monkstrap",
    image: require("../images/IMG31.jpg"),
    category: "monkstrap",
    // color: ["black"],
    price: 18000,
    details: "Black Croc-Skin Leather Monkstrap",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "28",
    name: "Brown Basket and Croc-Skin Leather Mules with Horse-bit Chain",
    image: require("../images/IMG16.jpg"),
    category: "mules",
    // color: ["brown"],
    price: 18000,
    details: "Black Basket and Croc-Skin Leather Mules with Horse-bit Chain",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "29",
    name: "Black Glossy Croc-Skin Mules with Horse-bit Chain",
    image: require("../images/IMG30.jpg"),
    category: "mules",
    // color: ["black"],
    price: 18000,
    details: "Black Glossy Croc-Skin Mules with Horse-bit Chain",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "30",
    name: "Black Glossy Lace-Up",
    image: require("../images/IMG35.jpg"),
    category: "laceup",
    // color: ["black"],
    price: 18000,
    details: "Black Glossy Lace-Up",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "31",
    name: "Black Shoe-Sandals",
    image: require("../images/IMG44.jpg"),
    category: "shoesandals",
    // color: ["black"],
    price: 18000,
    details: "Black Shoe-Sandals",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "32",
    name: "Black Shoe-Sandals",
    image: require("../images/IMG45.jpg"),
    category: "shoesandals",
    // color: ["black"],
    price: 18000,
    details: "Black Shoe-Sandals",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "33",
    name: "Black Shoe-Sandals",
    image: require("../images/IMG46.jpg"),
    category: "shoesandals",
    // color: ["black"],
    price: 18000,
    details: "Black Shoe-Sandals",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "34",
    name: "Black Leather Loafers with Tassels",
    image: require("../images/IMG40.jpg"),
    category: "loafers",
    // color: ["black"],
    price: 18000,
    details: "Black Leather Loafers with Tassels",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "35",
    name: "Black Glossy and Croc-Skin Loafers with Tassels",
    image: require("../images/IMG41.jpg"),
    category: "loafers",
    // color: ["black"],
    price: 18000,
    details: "Black Glossy and Croc-Skin Loafers with Tassels",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "36",
    name: "Black Croc-Skin Leather Mules",
    image: require("../images/IMG43.jpg"),
    category: "mules",
    // color: ["black"],
    price: 18000,
    details: "Black Croc-Skin Leather Mules",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "37",
    name: "Black Leather and Basket Leather Mules",
    image: require("../images/IMG42.jpg"),
    category: "shoesandals",
    // color: ["black"],
    price: 18000,
    details: "Black Leather and Basket Leather Mules",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
  {
    // id: "38",
    name: "Brown Suede Desert Boots",
    image: require("../images/IMG37.jpg"),
    category: "boots",
    // color: ["brown"],
    price: 1,
    details: "Brown Suede Desert Boots",
    // shoeSize: ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47"],
  },
];
